# Generated by Django 4.0.2 on 2022-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='proposal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='choice',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
