# Generated by Django 4.0.2 on 2022-02-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_down_votes_choice_proposal_choice_up_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='down_votes',
            new_name='down_vote',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='up_votes',
            new_name='up_vote',
        ),
    ]
