# Generated by Django 4.0.2 on 2022-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_down_votes_choice_down_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='proposal',
            field=models.TextField(),
        ),
    ]
